apiVersion: "tinkerbell.org/v1alpha1"
kind: Workflow
metadata:
  name: sandbox-workflow
  namespace: sff
spec:
  templateRef: ubuntu-focal
  hardwareRef: elite8200-1
  hardwareMap:
    device_1: e8:39:35:5c:e4:81